# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy WAR into image
COPY HelloWorld.java /app.java 
# compile application
CMD ["/usr/bin/javac", "/app.java"]
# run application with this command line
CMD ["/usr/bin/javac", "/app.class"]
